testarhamcollections_app/user_management/models.py
from ..extensions import db
import datetime
from flask_login import UserMixin, login_manager, current_user


class User(db.Model, UserMixin):

    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(80), unique=True, nullable=False)
    mobile_login = db.Column(db.String(15), unique=True, nullable=True)
    password = db.Column(db.String(256), nullable=False)
    creation_date = db.Column(db.DateTime, default=datetime.datetime.utcnow())
    updation_date = db.Column(db.DateTime, onupdate=datetime.datetime.utcnow())
    is_active = db.Column(db.Boolean, default=False)
    userprofiles = db.relationship("Userprofile", uselist=False, backref='user', lazy=True)
    useraddresses = db.relationship("Useraddress", backref="user", lazy=True)
    product = db.relationship("ProductMaster", backref="user", lazy=True)
    productimage = db.relationship("ProductImageMapping", backref="user", lazy=True)
    email_salt = db.Column(db.String(256), nullable=False)
    confirmed_on = db.Column(db.DateTime)

    def __repr__(self):
        return '<User %r>' % (self.email)

    def get_name(self):
        try:
            up = Userprofile.query.filter_by(user_id=self.id).first()
            name = (" ".join([up.first_name, up.last_name])).title()
        except:
            name = self.email
        # if not up.first_name == None and not up.last_name == None:
         # name = (" ".join([up.first_name, up.last_name])).title()
        # else:
        #     name = self.email
        return name

    # def get_id(self):
    #     """Return the email address to satisfy Flask-Login's requirements."""
    #     return self.email


class Userprofile(db.Model):

    __tablename__ = 'userprofile'

    profile_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    gender = db.Column(db.String(6))
    mobile_number = db.Column(db.String(15))
    creation_date = db.Column(db.DateTime, default=datetime.datetime.utcnow())
    updation_date = db.Column(db.DateTime, onupdate=datetime.datetime.utcnow())
    dateofbirth = db.Column(db.Date)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)


class Useraddress(db.Model):

    __tablename__ = 'useraddress'

    address_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    address1 = db.Column(db.String(256))
    address2 = db.Column(db.String(256))
    landmark = db.Column(db.String(256))
    state = db.Column(db.String(100))
    city = db.Column(db.String(75))
    pincode = db.Column(db.String(10))
    mobileno = db.Column(db.String(15))
    default_flag = db.Column(db.Boolean, default=False)
    delete_flag = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)


class Userroles(db.Model):

    __tablename__ = 'userroles'

    role_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    role = db.Column(db.String(80), nullable=False)
    creation_date = db.Column(db.DateTime, default=datetime.datetime.utcnow())
    updation_date = db.Column(db.DateTime, onupdate=datetime.datetime.utcnow())


class Userrolesmapping(db.Model):
    __tablename__ = 'userrolemapping'

    mapping_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    role_id = db.Column(db.Integer, db.ForeignKey('userroles.role_id'), nullable=False)

testarhamcollections_app/user_management/forms.py
from flask_wtf import Form, FlaskForm
from wtforms import StringField, PasswordField, SelectField, DateField, BooleanField, validators


class SignupForm(FlaskForm):
    email = StringField("Email", [validators.DataRequired(), validators.Email()])
    password = PasswordField("Password", [validators.DataRequired()])
    confirm_password = PasswordField("Confirm_Password", [validators.DataRequired()])


class LoginForm(FlaskForm):
    email = StringField("Email", [validators.Email()])
    password = PasswordField("Password", [validators.DataRequired()])


class ProfileForm(FlaskForm):
    first_name = StringField("First Name")
    last_name = StringField("Last Name")
    gender = SelectField("Gender", choices=[('male', 'Male'), ('female', 'Female')])
    mobile_number = StringField("Contact No", [validators.length(10, 10)])
    dateofbirth = DateField("Date Of Birth", format='%Y-%m-%d')


class AddAddressForm(FlaskForm):
    first_name = StringField("First Name", [validators.DataRequired()])
    last_name = StringField("Last Name", [validators.DataRequired()])
    address1 = StringField("Address1", [validators.DataRequired(), validators.length(25, 150)])
    address2 = StringField("Address2")
    landmark = StringField("Land Mark", [validators.DataRequired(), validators.length(15, 150)])
    state = StringField("State", [validators.DataRequired()])
    city = StringField("City", [validators.DataRequired()])
    pincode = StringField("Pin Code", [validators.DataRequired(), validators.length(6, 6)])
    mobileno = StringField("Mobile No", [validators.DataRequired(), validators.length(10, 10)])
    default_flag = BooleanField("Default Flag")


class ChangePasswordForm(FlaskForm):
    current_password = PasswordField("Current Password", [validators.DataRequired()])
    new_password = PasswordField("New Password", [validators.DataRequired()])
    confirm_password = PasswordField("Confirm Password", [validators.DataRequired()])


class ForgotPasswordForm(FlaskForm):
    email = StringField("Registered Email", [validators.DataRequired(), validators.Email()])


class PasswordResetForm(FlaskForm):
    new_password = PasswordField("New Password", [validators.DataRequired()])
    confirm_password = PasswordField("Confirm Password", [validators.DataRequired()])

testarhamcollections_app/user_management/views.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, current_app, session, abort, jsonify
from forms import SignupForm, LoginForm, ProfileForm, AddAddressForm, ChangePasswordForm, ForgotPasswordForm, PasswordResetForm
from werkzeug.security import check_password_hash, generate_password_hash
from models import (User, Userroles, Userrolesmapping, Userprofile, Useraddress
                    )
from ..extensions import db, login_manager

from itsdangerous import URLSafeTimedSerializer
from ..extensions import mail
from flask_login import login_user, logout_user, login_required, current_user


from flask_mail import Message
import random
import hashlib
from sqlalchemy import exc, and_, or_
import datetime
from flask_principal import identity_changed, AnonymousIdentity, Identity, Permission, RoleNeed, UserNeed
from collections import namedtuple
from flask_principal import identity_loaded
# from ..extensions import celery
# from celery.decorators import periodic_task
# from celery.task.schedules import crontab
import random

from datetime import timedelta



user_management = Blueprint('user_management', __name__, url_prefix="/", static_folder='./static', static_url_path="main_app/static", template_folder='./templates')
# from .extensions import db


app = current_app
admin_permission = Permission(RoleNeed('Admin'))
AddressNeed = namedtuple('AddressNeed', ['action', 'address_id'])


class AddressPermission(Permission):
    """Extend Permission to take a post_id and action as arguments"""

    def __init__(self, action, address_id=None):
        need = AddressNeed(action, address_id)
        # super(AddressPermission, self).__init__(need)
        super(AddressPermission, self).__init__(need)


@user_management.route("login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == "POST":
        if form.validate():
            x = request.form.to_dict()
            user = User.query.filter_by(email=x['email']).first()
            if user:
                if check_password_hash(user.password, x['password'] + user.email_salt):
                    login_user(user)
                    identity_changed.send(current_app._get_current_object(), identity=Identity(user.id))
                    return jsonify(success='logged in', redirect='/')
                else:
                    return jsonify(error='Incorrect password')
            else:
                return jsonify(error='Username not registered')
        else:
            return jsonify(fielderror=form.errors)
    else:
        return render_template('user_management/loginpage.html', form=form)


@login_required
@user_management.route("logout")
def logout():

    logout_user()
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)
    # identity_changed.send(current_app._get_current_object(), identity=AnonymousIdentity())
    identity_changed.send(current_app, identity=AnonymousIdentity())
    return redirect(url_for('main_app.home'))


@user_management.route("signup", methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if request.method == 'POST':
        if form.validate():
            x = request.form.to_dict()
            email = x['email']
            password = x['password']
            confirm_password = x['confirm_password']
            if password != confirm_password:
                return jsonify(error="ERROR! Passwords not matching.")
            # return render_template('user_management/signup.html', form=form)
            else:
                try:
                    salt = hashlib.sha1(str(random.random())).hexdigest()[:10]
                    password_hash = generate_password_hash(password + salt, 'sha256')
                    data = User(email=email, password=password_hash, email_salt=salt)
                    db.session.add(data)
                    db.session.commit()

                    userrole = Userroles.query.filter_by(role='User').first()
                    user_role_mapping = Userrolesmapping(user_id=data.id, role_id=userrole.role_id)
                    db.session.add(user_role_mapping)
                    db.session.commit()

                    userprofile = Userprofile(user_id=data.id)
                    db.session.add(userprofile)
                    db.session.commit()

                    # send_confirmation_email(email)
                    return jsonify(success='Please check you email')
                except exc.IntegrityError:
                    db.session.rollback()
                    error = 'ERROR! Email ({}) already exists.'.format(email)
                    return jsonify(error=error)
        else:
            return jsonify(fielderror=form.errors)
                # return render_template('user_management/signup.html', form=form)
    return render_template('user_management/signup.html', form=form)


@user_management.route("email", methods=['GET', 'POST'])
def email():
    return render_template('user_management/email.html')


def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])

    confirm_url = url_for(
        'user_management.confirm_email',
        token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'),
        _external=True)

    html = render_template(
        'user_management/email.html',
        confirm_url=confirm_url)

    msg = Message('Confirmation Email', sender='registration@arhamcollections.com', recipients=[user_email])
    msg.html = html

    mail.send(msg)


@user_management.route("confirm/<token>")
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=84600)
    except:
        flash('The confirmation link is invalid or has expired.', 'error')
        return redirect(url_for('user_management.login'))

    user = User.query.filter_by(email=email).first()

    if user.is_active:
        flash("Email is already confirmed, please login")
        return redirect(url_for('user_management.login'))
    else:
        user.is_active = True
        user.confirmed_on = datetime.datetime.utcnow()
        db.session.add(user)
        db.session.commit()
        flash("Thank you for confirming email")
        return redirect(url_for('user_management.login'))
    return redirect(url_for('user_management.login'))


@user_management.route("edituserprofile", methods=['GET', 'POST'])
@login_required
def edituserprofile():
    form = ProfileForm()
    if request.method == 'POST':
        print('FORM IS POSTED BY POST')
        if form.validate():
            x = request.form.to_dict()
            try:
                data=Userprofile.query.filter_by(user_id=current_user.id).first()
                data.first_name=x['first_name'] 
                data.last_name=x['last_name']
                data.dateofbirth=x['dateofbirth']
                data.mobile_number=x['mobile_number']
                data.gender=x['gender']
                db.session.add(data)
                db.session.commit()
                return jsonify(success='Updated your profile successfully')
            except:
                db.session.rollback()
                return jsonify(error='Error while updating')
        else:
            return jsonify(fielderror=form.errors)    
    else:
        try:
            userprofile = Userprofile.query.filter_by(user_id=current_user.id).first()
            form = ProfileForm(obj=userprofile)
            form.populate_obj(userprofile)
            return render_template('user_management/edituserprofile.html', form=form)
        except: 
            return jsonify(error='Unable to find profilie')
    return render_template('user_management/edituserprofile.html', form=form)




@user_management.route("accountpage", methods=['GET', 'POST'])
@login_required
def accountpage():
    return render_template('user_management/accountpage.html')


@user_management.route("addresslist", methods=['GET'])
@login_required
def addresslist():
    useraddress = Useraddress.query.filter(Useraddress.user_id == current_user.id).filter(Useraddress.delete_flag == 0).all()
    return render_template('user_management/addresslist.html', useraddress=useraddress)


@user_management.route('addaddress', methods=['GET', 'POST'])
@user_management.route("addaddress/<int:address_id>", methods=['GET', 'POST'])
@login_required
def addaddress(address_id=None):
    # x=1/0
    form = AddAddressForm()
    if request.method=='POST':
        if form.validate():
            x=request.form.to_dict()
            try:
                x['default_flag']
                x['default_flag']=True

            except:
                x['default_flag']=False

            if address_id==None:
                try:
                    data = Useraddress(first_name=x['first_name'], last_name=x['last_name'], address1=x['address1'], address2=x['address2'], landmark=x['landmark'], state=x['state'], city=x['city'], pincode=x['pincode'], mobileno=x['mobileno'], default_flag=x['default_flag'],user_id=current_user.id)
                    db.session.add(data)
                    db.session.commit()
                    if  x['default_flag']==True:
                        try:
                            defaultadddata=Useraddress.query.filter(Useraddress.user_id==current_user.id).filter(Useraddress.address_id.address_id !=data.address_id).filter(Useraddress.default_flag==True).first()
                            defaultadddata.default_flag=False
                            db.session.commit()
                        except:
                            db.session.rollback()
                            return jsonify(error="You don't have any default adddress" )

testarhamcollections_app/user_management/templates/user_management/accountpage.html
{%extends 'main_app/base.html' %}
{% block content%}


<div class="row">
	<div class="col s12 m4 l3">
		<a href={{ url_for('user_management.edituserprofile') }}>
			<div class="card-panel z-depth-4">
				<span class="red-text"><h5>Your Profile</h5>
				</span>
				<p>This help us know you better.</p>
			</div>
		</a>
	</div>
	<div class="col s12 m4 l3">
		<a href={{ url_for('user_management.addresslist') }}>
			<div class="card-panel z-depth-4">
				<span class="red-text"><h5>Your Addresses</h5>
				</span>
				<p>Your addresses help you in quick checkout.</p>
			</div>
		</a>
	</div>
	<div class="col s12 m4 l3">
		<a href={{ url_for('user_management.changepassword') }}>
			<div class="card-panel z-depth-4">
			<span class="red-text"><h5>Change Password</h5>
			</span>
			<p>Keep your account safe.</p>
			</div>
		</a>
	</div>
	<div class="col s12 m4 l3">
		<a href="#">
			<div class="card-panel z-depth-4">
			<span class="red-text"><h5>Wish List</h5>
			</span>
			<p>Planning your shopping. Keep here whatever you like and want to buy.</p>
			</div>
		</a>
	</div>
</div>
<div class="row">
	<div class="col s12 m4 l3">
		<a href="#">
			<div class="card-panel z-depth-4">
			<span class="red-text"><h5>Your Orders</h5>
			</span>
			<p>Check status of your orders</p>
			</div>
		</a>
	</div>

</div>
	


{% endblock %}

testarhamcollections_app/user_management/templates/user_management/addaddress.html
{%extends 'main_app/base.html' %}

{% block content %}
       
<div class="row">
	<div class="row">
		<div class="card-panel grey lighten-2 col s12 m8 l6 offset-l3 m2">
			<span class="red-text"><h5>Add Address{{form.landmark.data}}</h5>
			</span>
		</div>
	</div>
	<form  method="POST">
		<div class="row">
			<div class="row">
				<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<input id="first_name"  type="text" name="first_name" class="validate" value={%if address_id==None%}{{""}}{%else%}"{{form.first_name.data}}"{%endif%}>
					<label for="first_name" >First Name</label>
				</div>
			</div>
			<div class="row">	
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<input id="last_name"   type="text" name="last_name" class="validate" value={%if address_id==None%}{{""}}{%else%}"{{form.last_name.data}}"{%endif%} >
					<label for="last_name" >Last Name</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<input id="landmark"  type="text" name="landmark" class="validate" value={%if address_id==None%}{{""}}{%else%}"{{form.landmark.data}}"{%endif%}>
					<label for="landmark">Landmark</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<input id="address1" type="text" name="address1" class="validate" value={%if address_id==None%}{{""}}{%else%}"{{form.address1.data}}"{%endif%}>
					<label for="address1">Address</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<input id="address2" type="text" name="address2" class="validate" value={%if address_id==None%}{{""}}{%else%}"{{form.address2.data}}"{%endif%}>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<input id="state" type="text" name="state" class="validate" value={%if address_id==None%}{{""}}{%else%}"{{form.state.data}}"{%endif%}>
					<label for="state">State</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<input id="city" type="text" name="city" class="validate" value={%if address_id==None%}{{""}}{%else%}"{{form.city.data}}"{%endif%}>
					<label for="city">City</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<input id="pincode" type="text" name="pincode" class="validate" value={%if address_id==None%}{{""}}{%else%}"{{form.pincode.data}}"{%endif%}>
					<label for="pincode">Pincode</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<input id="mobileno" type="text" name="mobileno" class="validate" value={%if address_id==None%}{{""}}{%else%}"{{form.mobileno.data}}"{%endif%}>
					<label for="mobileno">Mobile No</label>
				</div>
			</div>
			<div class="row">
				<div class="col s12 m8 l6 offset-l3 m2">
					<input type="checkbox"  id="default_flag" name="default_flag" {%if form.default_flag.data==True%}{{'checked=checked'}}{%endif%}/>
		      		<label for="default_flag">Set Default</label>
		      	</div>
      		</div>

      		<div class="row">
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<button type="submit" class="btn cyan waves-effect waves-light col s12">Save</button>
				</div>
			</div>
		</div>

	</form>
	<div class="col s12 m8 l6 offset-l3 m2">
		<div class="row">
			<div class="row" id ="success">
				 <div class="success-msg">
					
				 </div>					 
			</div>
			<div class="row" id ="error">
				 <div class="error-msg">
					
				 </div>					 
			</div>
		</div>
	</div>	

</div>


{% endblock %}



{% block endjs%}
{{super()}}
<script>


$(document).ready(function(event)
	{
	$('#success').hide()
	$('#error').hide()

	var url;
	url = "{{ url_for('user_management.addaddress',address_id=address_id)}}";
	

		$('form').on('submit',function(event)
		{

		// $('#first_name').removeClass('invalid');
		// $('#first_name').removeAttr( "aria-invalid" )
		// $('#last_name').removeClass('invalid');
		// $('#last_name').removeAttr( "aria-invalid" )
		$.ajax({
				type:"POST",
				url:url,
				data:$('form').serialize(),

				})
		.done(function(data){

					
					ShowMessage(data);

					if (data.fielderror)
						{
						$.each(data.fielderror,function(datakey,datavalue){
							$('form input').each(function(key,value){
								if (this.id==datakey){
									$('label[for="'+datakey +'"]').attr('data-error',datavalue);
									$(this).addClass('invalid');
									$(this).prop('aria-valid',"true");
									$('label[for="'+datakey +'"]').addClass('active');
									}

							});    
						});
						}
							});
	event.preventDefault();
	});

});


</script>

{% endblock%}

testarhamcollections_app/user_management/templates/user_management/addresslist.html
{% extends 'main_app/base.html' %}
{% block content %}


<div class="row">
	{% if useraddress==None %}
	<div class="col s12 m4 l3">
		<a href={{ url_for('user_management.addaddress') }}>
			<div class="card z-depth-4">
				<div class="card-content">
				<span class="card-title">Add Address</span>
				<p>Add your addresses here</p>
				</div>
			</div>
		</a>
	</div>	
	{% endif %}
	{%for ua in useraddress %}
	<div class="col s12 m4 l3">
		<div class="card z-depth-4">
		<div class="card-content">
			<span class="card-title">{{ua.first_name}} {{ua.last_name}}  </span>
			<p>{{ua.address1}}</p>
			<p>{{ua.address2}}</p>
			<p>{{ua.landmark}}</p>
			<p>{{ua.state}}</p>
			<p>{{ua.city}}</p>
			<p>{{ua.pin}}</p>
			<p>{{ua.mobileno}}</p>
		</div>
		<div class="card-action">
		<a href={{ url_for('user_management.addaddress',address_id=ua.address_id)}}>Edit</a>
		<a href={{ url_for('user_management.deleteaddress',address_id=ua.address_id)}}>Delete</a>
		{% if ua.default_flag==1 %} 
				 <i class="material-icons">flag</i>{% endif %}
		</div>
		</div>
	</div>
	{%endfor%}
	{% if useraddress!=None %}
	<div class="col s12 m4 l3">
		<a href={{ url_for('user_management.addaddress') }}>
			<div class="card z-depth-4">
				<div class="card-content">
				<span class="card-title">Add More Addresses</span>
				<p>Add your addresses here</p>
				</div>
			</div>
		</a>
	</div>	
	{% endif %}

</div>
{% endblock %}

testarhamcollections_app/user_management/templates/user_management/edituserprofile.html
{%extends 'main_app/base.html' %}
{% block content%}
<div class="row">
	<div class="row">
		<div class="card-panel grey lighten-2 col s12 m8 l6 offset-l3 m2">
			<span class="red-text"><h5>Your Profile</h5>
			</span>
		</div>
	</div>
	<form method="POST">
		<div class="row">
			<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
			<div class="row">
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<input id="first_name" type="text"  name="first_name" value="{{form.first_name.data}}">
					<label for="first_name">First Name</label>
				</div>
			</div>
			<div class="row">	
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<input id="last_name" type="text" name="last_name" value="{{form.last_name.data}}">
					<label for="last_name">Last Name</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m8 l4 offset-l3 m2">
					<select id="gender" name="gender" value={{form.gender.data}}>>
						<option value="" disable selected>Select Gender</option>
						<option value="female" {%if form.gender.data=="female"%}{{"selected"}}{% endif%}>Female</option>
						<option value="male" {%if form.gender.data=="male"%}{{"selected"}}{% endif%}>Male</option>
					</select>
					<label>Gender</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<input id="mobile_number" type="text" class="validate" name="mobile_number" value="{{form.mobile_number.data}}">
					<label for="mobile_number">Moblie Number</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<!-- {{form.dateofbirth(class="datepicker") }} -->
					<input id="dateofbirth" name="dateofbirth" type="date" class="datepicker" value="{{form.dateofbirth.data}}">
					<label for="dateofbirth">Date of Birth</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m8 l6 offset-l3 m2">
					<button type="submit" class="btn cyan waves-effect waves-light col s12">Save</button>
				</div>
			</div>
		</div>
	</form>
	<div class="col s12 m8 l6 offset-l3 m2">
		<div class="row">
			<div class="row" id ="success">
				 <div class="success-msg">
					
				 </div>					 
			</div>
			<div class="row" id ="error">
				 <div class="error-msg">
					
				 </div>					 
			</div>
		</div>
	</div>	
</div>
	


{% endblock %}




{% block endjs%}
{{super()}}
<script>


$(document).ready(function(event)
	{
	$('#success').hide()
	$('#error').hide()

	var url;
	url = "{{ url_for('user_management.edituserprofile')}}";
	

		$('form').on('submit',function(event)
		{

		// $('#first_name').removeClass('invalid');
		// $('#first_name').removeAttr( "aria-invalid" )
		// $('#last_name').removeClass('invalid');
		// $('#last_name').removeAttr( "aria-invalid" )
		$.ajax({
				type:"POST",
				url:url,
				data:$('form').serialize(),


				})
		.done(function(data){

					
					ShowMessage(data);

					if (data.fielderror)
						{
						$.each(data.fielderror,function(datakey,datavalue){
							$('form input').each(function(key,value){
								if (this.id==datakey){
									$('label[for="'+datakey +'"]').attr('data-error',datavalue);
									$(this).addClass('invalid');
									$(this).prop('aria-valid',"true");
									$('label[for="'+datakey +'"]').addClass('active');
									}

							});    
						});
						}
							});
	event.preventDefault();
	});

});


</script>

{% endblock%}

testarhamcollections_app/user_management/templates/user_management/email.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Arhamcollections confirmation</title>
</head>
<body>
<style>
#titlebox {
	display: inline-block;
	width:100%;
	height:100px;
	background: red;
	color:white;
	position: : relative;
}

h5 {
	font-family: "Trebuchet MS","Courier New", Helvetica,verdana;
	font-size:24px;
	font-weight: bold;
	vertical-align: middle;
	padding-left: 20px;
}

p {
    font-family: "Trebuchet MS","Courier New", Helvetica,verdana;
    font-size: 20px;
}
#activate {
	background: #9ccc65 ;
	color :white;
	font-size: 20px;
	font-weight: bold;
	border: 1px solid #aed581;
	padding-left: 15px;
	padding-right: 15px;
	padding-top: 5px;
	padding-bottom: 5px;
	border-radius: 7px;
	
}

#title {
	color:white;
	text-decoration: none;
	font-family: verdana;
}

#activate:hover {
	background: #8bc34a ;
	}
</style>
	<div id="titlebox">
		<h5><a id="title" href="arhamcollections.com">Arham Collections</a></h5>
	</div>
	<p>
		Welcome to Arham Collections.
	</p>		
	<p>
		Click on the link below to activate your account and start your journey of shopping at best rates.
	</p>

	<a href="{{ confirm_url }}" id="activate">Activate</a>	
</body>
</html>

testarhamcollections_app/user_management/templates/user_management/signupsuccess.html
{%extends 'main_app/base.html' %}
{% block content%}


<div class="row">
	<p>Successfully signed up, check your email for activation</p>
</div>

{% endblock%}