testarhamcollections_app/main_app/views.py
from flask import Blueprint, render_template, url_for, redirect, flash, request

from random import randint
main_app = Blueprint('main_app', __name__, url_prefix="/", static_folder='./static', static_url_path="main_app/static", template_folder='./templates')
# from .extensions import db
from ..extensions import db
from ..models import Testset
from ..product_management.models import MenuMaster, SubMenuMaster
# from models import VoteTest

from ..user_management.models import User, Userprofile, Userroles
from ..extensions import mail
from flask_mail import Message

# from ..app import allowed_file

from ..user_management.views import send_confirmation_email

from werkzeug.utils import secure_filename
import os


@main_app.route("/", methods=['GET', 'POST'])
def home():
    # send_confirmation_email('admin@arhamcollections.com')
    # menus = db.engine.execute('CALL GET_MENU')
    # submenu = db.engine.execute('CALL GET_SUBMENU')
    # x = menus.fetchall()
    # y = submenu.fetchall()
    return render_template('main_app/index.html')


# @main_app.context_processor
# def test():
#     menus = db.engine.execute('CALL GET_MENU')
#     submenu = db.engine.execute('CALL GET_SUBMENU')
#     x = menus.fetchall()
#     y = submenu.fetchall()
#     return dict(menus=x, submenu=y)


@main_app.route("faq", methods=['GET', 'POST'])
def faq():

    # msg = Message('Hello', sender = 'registration@arhamcollections.com', recipients = ['findsarfaraz@gmail.com'])
    # msg.body = "Hello Flask message sent from Flask-Mail"
    # mail.send(msg)
    return render_template('main_app/faq.html')


@main_app.route("create")
def create():
    db.create_all()
    return "all tables created"


@main_app.route("dropall")
def dropall():
    db.drop_all()
    return "all tables dropped"


@main_app.route("createroles")
def createroles():
    userroles = Userroles(role="Admin")
    db.session.add(userroles)
    db.session.commit()
    userroles = Userroles(role="User")
    db.session.add(userroles)
    db.session.commit()
    return "added all roles"


@main_app.route("imageupload", methods=['GET', 'POST'])
def imageupload():
    for file in request.files.getlist('file'):
        path = "/".join([os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')), "images"])
        print path
        filename = file.filename
        print filename
        destination = "/".join([path, filename])
        file.save(destination)

    return render_template('main_app/imageupload.html')


@main_app.route("testpath", methods=['GET', 'POST'])
def testpath():
    path = "/".join([os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')), "images"])
    print path
    return render_template('main_app/imageupload.html')

# def allowed_file(filename):
#     return '.' in filename and \
#            filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


# @main_app.errorhandler(403)
# def page_not_found(e):
#     return render_template('403.html'), 403


# @main_app.errorhandler(410)
# def page_not_found(e):
#     return render_template('410.html'), 410


@main_app.route("admin", methods=['GET', 'POST'])
def admin():
    return render_template('main_app/admin.html')


@main_app.route("fblogin", methods=['GET', 'POST'])
def fblogin():
    return render_template('main_app/fblogin.html')

testarhamcollections_app/user_management/views.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, current_app, session, abort, jsonify
from forms import SignupForm, LoginForm, ProfileForm, AddAddressForm, ChangePasswordForm, ForgotPasswordForm, PasswordResetForm
from werkzeug.security import check_password_hash, generate_password_hash
from models import (User, Userroles, Userrolesmapping, Userprofile, Useraddress
                    )
from ..extensions import db, login_manager

from itsdangerous import URLSafeTimedSerializer
from ..extensions import mail
from flask_login import login_user, logout_user, login_required, current_user


from flask_mail import Message
import random
import hashlib
from sqlalchemy import exc, and_, or_
import datetime
from flask_principal import identity_changed, AnonymousIdentity, Identity, Permission, RoleNeed, UserNeed
from collections import namedtuple
from flask_principal import identity_loaded
# from ..extensions import celery
# from celery.decorators import periodic_task
# from celery.task.schedules import crontab
import random

from datetime import timedelta



user_management = Blueprint('user_management', __name__, url_prefix="/", static_folder='./static', static_url_path="main_app/static", template_folder='./templates')
# from .extensions import db


app = current_app
admin_permission = Permission(RoleNeed('Admin'))
AddressNeed = namedtuple('AddressNeed', ['action', 'address_id'])


class AddressPermission(Permission):
    """Extend Permission to take a post_id and action as arguments"""

    def __init__(self, action, address_id=None):
        need = AddressNeed(action, address_id)
        # super(AddressPermission, self).__init__(need)
        super(AddressPermission, self).__init__(need)


@user_management.route("login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == "POST":
        if form.validate():
            x = request.form.to_dict()
            user = User.query.filter_by(email=x['email']).first()
            if user:
                if check_password_hash(user.password, x['password'] + user.email_salt):
                    login_user(user)
                    identity_changed.send(current_app._get_current_object(), identity=Identity(user.id))
                    return jsonify(success='logged in', redirect='/')
                else:
                    return jsonify(error='Incorrect password')
            else:
                return jsonify(error='Username not registered')
        else:
            return jsonify(fielderror=form.errors)
    else:
        return render_template('user_management/loginpage.html', form=form)


@login_required
@user_management.route("logout")
def logout():

    logout_user()
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)
    # identity_changed.send(current_app._get_current_object(), identity=AnonymousIdentity())
    identity_changed.send(current_app, identity=AnonymousIdentity())
    return redirect(url_for('main_app.home'))


@user_management.route("signup", methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if request.method == 'POST':
        if form.validate():
            x = request.form.to_dict()
            email = x['email']
            password = x['password']
            confirm_password = x['confirm_password']
            if password != confirm_password:
                return jsonify(error="ERROR! Passwords not matching.")
            # return render_template('user_management/signup.html', form=form)
            else:
                try:
                    salt = hashlib.sha1(str(random.random())).hexdigest()[:10]
                    password_hash = generate_password_hash(password + salt, 'sha256')
                    data = User(email=email, password=password_hash, email_salt=salt)
                    db.session.add(data)
                    db.session.commit()

                    userrole = Userroles.query.filter_by(role='User').first()
                    user_role_mapping = Userrolesmapping(user_id=data.id, role_id=userrole.role_id)
                    db.session.add(user_role_mapping)
                    db.session.commit()

                    userprofile = Userprofile(user_id=data.id)
                    db.session.add(userprofile)
                    db.session.commit()

                    # send_confirmation_email(email)
                    return jsonify(success='Please check you email')
                except exc.IntegrityError:
                    db.session.rollback()
                    error = 'ERROR! Email ({}) already exists.'.format(email)
                    return jsonify(error=error)
        else:
            return jsonify(fielderror=form.errors)
                # return render_template('user_management/signup.html', form=form)
    return render_template('user_management/signup.html', form=form)


@user_management.route("email", methods=['GET', 'POST'])
def email():
    return render_template('user_management/email.html')


def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])

    confirm_url = url_for(
        'user_management.confirm_email',
        token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'),
        _external=True)

    html = render_template(
        'user_management/email.html',
        confirm_url=confirm_url)

    msg = Message('Confirmation Email', sender='registration@arhamcollections.com', recipients=[user_email])
    msg.html = html

    mail.send(msg)


@user_management.route("confirm/<token>")
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=84600)
    except:
        flash('The confirmation link is invalid or has expired.', 'error')
        return redirect(url_for('user_management.login'))

    user = User.query.filter_by(email=email).first()

    if user.is_active:
        flash("Email is already confirmed, please login")
        return redirect(url_for('user_management.login'))
    else:
        user.is_active = True
        user.confirmed_on = datetime.datetime.utcnow()
        db.session.add(user)
        db.session.commit()
        flash("Thank you for confirming email")
        return redirect(url_for('user_management.login'))
    return redirect(url_for('user_management.login'))


@user_management.route("edituserprofile", methods=['GET', 'POST'])
@login_required
def edituserprofile():
    form = ProfileForm()
    if request.method == 'POST':
        print('FORM IS POSTED BY POST')
        if form.validate():
            x = request.form.to_dict()
            try:
                data=Userprofile.query.filter_by(user_id=current_user.id).first()
                data.first_name=x['first_name'] 
                data.last_name=x['last_name']
                data.dateofbirth=x['dateofbirth']
                data.mobile_number=x['mobile_number']
                data.gender=x['gender']
                db.session.add(data)
                db.session.commit()
                return jsonify(success='Updated your profile successfully')
            except:
                db.session.rollback()
                return jsonify(error='Error while updating')
        else:
            return jsonify(fielderror=form.errors)    
    else:
        try:
            userprofile = Userprofile.query.filter_by(user_id=current_user.id).first()
            form = ProfileForm(obj=userprofile)
            form.populate_obj(userprofile)
            return render_template('user_management/edituserprofile.html', form=form)
        except: 
            return jsonify(error='Unable to find profilie')
    return render_template('user_management/edituserprofile.html', form=form)




@user_management.route("accountpage", methods=['GET', 'POST'])
@login_required
def accountpage():
    return render_template('user_management/accountpage.html')


@user_management.route("addresslist", methods=['GET'])
@login_required
def addresslist():
    useraddress = Useraddress.query.filter(Useraddress.user_id == current_user.id).filter(Useraddress.delete_flag == 0).all()
    return render_template('user_management/addresslist.html', useraddress=useraddress)


@user_management.route('addaddress', methods=['GET', 'POST'])
@user_management.route("addaddress/<int:address_id>", methods=['GET', 'POST'])
@login_required
def addaddress(address_id=None):
    # x=1/0
    form = AddAddressForm()
    if request.method=='POST':
        if form.validate():
            x=request.form.to_dict()
            try:
                x['default_flag']
                x['default_flag']=True

            except:
                x['default_flag']=False

            if address_id==None:
                try:
                    data = Useraddress(first_name=x['first_name'], last_name=x['last_name'], address1=x['address1'], address2=x['address2'], landmark=x['landmark'], state=x['state'], city=x['city'], pincode=x['pincode'], mobileno=x['mobileno'], default_flag=x['default_flag'],user_id=current_user.id)
                    db.session.add(data)
                    db.session.commit()
                    if  x['default_flag']==True:
                        try:
                            defaultadddata=Useraddress.query.filter(Useraddress.user_id==current_user.id).filter(Useraddress.address_id.address_id !=data.address_id).filter(Useraddress.default_flag==True).first()
                            defaultadddata.default_flag=False
                            db.session.commit()
                        except:
                            db.session.rollback()
                            return jsonify(error="You don't have any default adddress" )

testarhamcollections_app/main_app/templates/main_app/admin.html
{%extends 'main_app/base.html' %}

{% block content%}

  <div class="row">
    <div class="col s6 m3">
      <div class="card grey lighten-3">
        <div class="card-content">
          <span class="card-title">Manage Menu</span>
        </div>
        <div class="card-action">
          <p><a href={{ url_for('product_management.addmenu') }}>Add Menu</a></p>
          <p><a href={{ url_for('product_management.addsubmenu') }}>Add Sub Menu</a></p>
          <p><a href={{ url_for('product_management.menulist') }}>Menu List</a></p>
        </div>
      </div>
    </div>
    <div class="col s6 m3">
      <div class="card grey lighten-3">
        <div class="card-content">
          <span class="card-title">Manage User</span>
        </div>
        <div class="card-action">
          <p><a href={{ url_for('product_management.addmenu') }}>Add Menu</a></p>
          <p><a href="#">This is a link</a></p>
        </div>
      </div>
    </div>
    <div class="col s6 m3">
      <div class="card grey lighten-3">
        <div class="card-content">
          <span class="card-title">Manage Products</span>
        </div>
        <div class="card-action">
          <p><a href="#">Add Product</a></p>
          <p><a href="#">Product Pending Review/a></p>
        </div>
      </div>
    </div>
    <div class="col s6 m3">
      <div class="card grey lighten-3">
        <div class="card-content">
          <span class="card-title">Manage Orders</span>
        </div>
        <div class="card-action">
          <p><a href="#">This is a link</a></p>
          <p><a href="#">This is a link</a></p>
        </div>
      </div>
    </div>
  </div>
            

{%endblock%}

testarhamcollections_app/main_app/templates/main_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{%block title%}Arham Collections{%endblock%}</title>
	 <link href="{{ url_for('main_app.static',filename='css/materialize.min.css') }}" rel="stylesheet">
	 <link href="{{ url_for('main_app.static',filename='css/fontawesome.min.css') }}" rel="stylesheet">
	 <link href="{{ url_for('main_app.static',filename='css/custom.css') }}" rel="stylesheet">
	 <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
		
</head>
<body>
{%block startjs%}
<script type=text/javascript>
  $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};

</script>


{% endblock %}

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->




<main>
<div class="row">

    {%include 'main_app/navbar.html'%}

    
		
</div>

<div class="container">
    {% block content%}
    <div class="row">


      {% endblock %}
    </div>  
</div>
</main>
<div>
	{%include 'main_app/footer.html'%}
</div>

{%block endjs%}

<script type="text/javascript" src="{{ url_for('main_app.static',filename='js/jquery.min.js')}}"></script>
<script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/materialize.min.js')}}"></script>
<script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/fontawesome-all.js')}}"></script>
<script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/ajax_csrf.js')}}"></script>
<script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/custom.js')}}"></script>







 {%endblock%}


</body>
</html>

testarhamcollections_app/main_app/templates/main_app/blankbase.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	 <link href="{{ url_for('main_app.static',filename='css/materialize.min.css') }}" rel="stylesheet">
	 <link href="{{ url_for('main_app.static',filename='css/fontawesome.min.css') }}" rel="stylesheet">
	 <link href="{{ url_for('main_app.static',filename='css/custom.css') }}" rel="stylesheet">
	 <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

		
</head>
<body class="red darken-1">
<main>


<div class="container">
    {% block content%}



    {% endblock %}
	
</div>
</main>


{%block endjs%}

<script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/jquery.min.js')}}"></script>
<script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/materialize.min.js')}}"></script>
<script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/fontawesome-all.js')}}"></script>
<script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/custom.js')}}"></script>
<script>$(".button-collapse").sideNav();</script>


 {%endblock%}


</body>
</html>

testarhamcollections_app/main_app/templates/main_app/breadcrumb.html
<nav>
	<div class="nav-wrapper">
	  <div class="container">
	  <div class="col s12">
	    <a href="#!" class="breadcrumb">First</a>
	    <a href="#!" class="breadcrumb">Second</a>
	    <a href="#!" class="breadcrumb">Third</a>
	  </div>
	   </div>
	</div>
</nav>

testarhamcollections_app/main_app/templates/main_app/faq.html
{%extends 'main_app/base.html' %}

{% block content%}
<ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header">Why order only on whatsapp</div>
      <div class="collapsible-body"><span>We are working on making placing order on our website</span></div>
    </li>
    <li>
      <div class="collapsible-header">Second</div>
      <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
    </li>
    <li>
      <div class="collapsible-header">Third</div>
      <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
    </li>
  </ul>

{%endblock%}

testarhamcollections_app/main_app/templates/main_app/footer.html
<div class="divider"></div>
<footer class="page-footer grey lighten-3">
  <div class="container">
    <div class="row">
      {%include 'main_app/footercontact.html'%}
    </div>  
  </div>

  <div class="divider"></div>  

  <div class="container">
    <div class="row">
      {%include 'main_app/footerlink.html'%}
    </div>
  </div>
 
  <div class="footer-copyright grey lighten-2">
    <div class="container">
      <div class="row">
        {%include 'main_app/footercopyright.html'%}
      </div>
    </div>
  </div>
</footer>

testarhamcollections_app/main_app/templates/main_app/footer1.html
<footer class="page-footer grey lighten-3">
  <div class="container">
    <div class="row">
      {%include 'main_app/footercontact.html'%}
    </div>
  </div>
</footer>
<div class="divider"></div>
<footer class="page-footer grey lighten-4">
  <div class="container">
    <div class="row">
      {%include 'main_app/footerlink.html'%}
    </div>
  </div>
</footer>


  <div class="footer-copyright grey lighten-2">
  <div class="container">
    <div class="row">
     {%include 'main_app/footercopyright.html'%}
    </div>
  </div>
</footer>

testarhamcollections_app/main_app/templates/main_app/footercontact.html
<div class="col s12 m12 l12">
  <div class="col s12 m6 l3">
    <h5 class="center-align" id ="footertitle">Join us here</h5>
      <div style="text-align: center;">
        <i id="footersocialicon" class="fab fa-facebook-square fa-3x style=display: inline-block;color:#e53935;"></i> &nbsp;&nbsp;&nbsp;
        <i id="footersocialicon" class="fab fa-twitter-square fa-3x  style=display: inline-block;"></i> &nbsp;&nbsp;&nbsp;
        <i id="footersocialicon"  class="fab fa-whatsapp-square fa-3x style=display: inline-block;"></i> &nbsp;&nbsp;&nbsp;
        <i id="footersocialicon" class="fab fa-instagram fa-3x style=display: inline-block;"></i> &nbsp;&nbsp;&nbsp;
      </div>
  </div>
  <div class="col s12 m6 l3">
    <h5 id ="footertitle">Email Us:</h5>
    <ul>
      <li> 
        <a href="#" id="footercontact">
        <div class="valign-wrapper">
          <div id="emailsocialicon"></div> 
           care@abc.com
        </div>
        
        </a>
      </li>
    </ul>
  </div>
  <div class="col s12 m6 l3">
    <h5 id="footertitle">Call Us:</h5>
    <ul>
      <li>
        <a href="#" id="footercontact">
          <div class="valign-wrapper">
            <div id="phonesocialicon"></div>
            9320089916
          </div>
        </a>
      </li>
    </ul> 
  </div>
  <div class="col s12 m6 l3">
    <h5 id="footertitle"> Read Our FAQ's </h5>
    <ul>
      <li>
        <a href={{ url_for('main_app.faq') }} id="footercontact">
          <div class="valign-wrapper">
          <div id="faqsocialicon" ></div>
            Click here
          </div>
        </a>
      </li>
    </ul>
  </div>

</div>

testarhamcollections_app/main_app/templates/main_app/footercopyright.html
<div class="col s12 m12 l12">
	<ul>
	  <li id="footernav"><span class="grey-text text-darken-3">© 2017 Copyright Text</span></li>
	  <li  class="right"><a id="footernav" href="sass.html">Terms and conditions</a></li>
	  <li  class="right"><a id="footernav" href="badges.html">FAQ</a></li>
	  <li  class="right"><a id="footernav" href="badges.html">Privacy Policy</a></li>
	  <li  class="right"><a id="footernav" href="badges.html">Become a seller</a></li>
	</ul>
</div>

testarhamcollections_app/main_app/templates/main_app/footerlink.html
<div class="col s12">
	<div class="col s12 m2 l2 hide-on-med-and-down">
		<ul>
		<li><div class="footerlinkheader">Dress</div></li>
		<a href="#" id="footerlink"><li>Alvin</li></a>
		<a href="#" id="footerlink"><li>Alvin</li> </a>
		<a href="#" id="footerlink"><li>Alvin</li></a>
		<a href="#" id="footerlink"><li >Alvin</li></a>
		</ul>
	</div>
	<div class="col s12 m2 l2 hide-on-med-and-down">
		<ul>
		<li><div class="footerlinkheader">Jewellery</div></li>
		<a href="#" id="footerlink"><li>Alvin</li></a>
		<a href="#" id="footerlink"><li>Alvin</li></a>
		<a href="#" id="footerlink"><li>Alvin</li></a>
		<a href="#" id="footerlink"><li>Alvin</li></a>
		</ul>
	</div>
	<div class="col s12 m2 l2  hide-on-med-and-down">
		<ul >
		<li><div class="footerlinkheader">Brands</div></li>
		<a href="#" id="footerlink"><li>Alvin</li></a>
		<a href="#" id="footerlink"><li>Alvin</li></a>
		<a href="#" id="footerlink"><li>Alvin</li></a>
		<a href="#" id="footerlink"><li>Alvin</li></a>
		</ul>
	</div>
	<div class="col s12 m2 l2  hide-on-med-and-down">
		<ul >
		<li><div class="footerlinkheader">Offers</div></li>
		<a href="#" id="footerlink"><li>Refer your friend</li></a>
		<a href="#" id="footerlink"><li>Discount Voucher</li></a>
		<a href="#" id="footerlink"><li>Like and Get</li></a>
		<a href="#" id="footerlink"><li>Festive Offer's</li></a>
		</ul>
	</div>
	<div class="col s12 m12 l4">
		<div class="row">
			<ul >
				<li><div class="footerlinkheader">Never Miss a Deal</div></li>
			</ul>
			<div class="card-panel s12 m12 l12">

			<form class="col s12 m12 l12">
				<div class="row">
					<div class="input-field col s7 m10 l10">
			      		<input id="email" type="email" class="validate black-text">
			      		<label for="email">Email</label>
			    	</div>
			    	<div>
			      		<button class="green waves-effect waves-light btn" type="submit" name="action">Subscribe</button>
			    	</div>
	        	</div>

			</form>
				<ul >
					<li id="footerlink">Get best deals and updates in your inbox</li>
				</ul>
			</div>
		</div>
	</div>
</div>

testarhamcollections_app/main_app/templates/main_app/imageupload.html
{% extends 'main_app/base.html' %}
{% block content %}

<div class="row">
	<form action={{ url_for('main_app.addproductimage') }} method="POST" enctype="multipart/form-data">
		<input type="file" id"file" name="file">
		<button type="submit">Submit</button>
	</form>
</div>

{% endblock %}

testarhamcollections_app/main_app/templates/main_app/index.html
{%extends 'main_app/base.html' %}
{%block title%}{{super()}}: Home{%endblock%}

{% block content%}


{% endblock %}

testarhamcollections_app/main_app/templates/main_app/navbar.html
<nav class="red darken-1">
    <div class="container">
	    <div class="nav-wrapper red darken-1">
		    <ul class="left">
		      <li>
		      	<a href={{ url_for('main_app.home') }} class="brand-logo">Logo</a>
		      </li>
		     </ul>
	     </div>
	     <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
	      <ul id="nav-mobile" class="right hide-on-med-and-down">
	        {% if current_user.is_authenticated %}
	        <li><a class="dropdown-button" href={{ url_for('user_management.accountpage') }} data-beloworigin="true" data-activates="dropdown1">{{current_user.get_name()}}<i class="material-icons right">arrow_drop_down</i></a></li>
	        <li><a href={{ url_for('user_management.logout') }}>Log Out</a></li>
	        {% else %}
	        <li><a href={{ url_for('user_management.login') }}>Login</a></li>
	        <li><a href={{ url_for('user_management.signup') }}>Sign Up</a></li>
			{% endif %}
	        <li><a href="collapsible.html"><i class="fas fa-shopping-cart fa-2x"></i></a></li>
	      </ul>
	       <ul class="side-nav" id="mobile-demo">
		        <li><a href="sass.html">Login</a></li>
		        <li><a href="badges.html">Sign Up</a></li>
		        <li><a href="collapsible.html"><i class="fas fa-shopping-cart fa-2x"></i></a></li>
		    </ul>
    </div>
</nav>    
{# Grey nav bar #}
<nav class="grey lighten-5 ">
	<div class="nav-wrapper">
		<div class="container">
		<ul class="left hide-on-med-and-down">
<!-- 			<li><a href="sass.html" class="red-text text-darken-1">Fashion</a></li>
			<li><a href="badges.html" class="red-text text-darken-1">Jewellery</a></li>
			<li><a href="badges.html" class="red-text text-darken-1">Footwear</a></li> -->
			{%for row in menus%}
			<li><a class="dropdown-button" href="badges.html" data-activates="menu{{row.menu_id}}"><span class="red-text text-darken-1">
				{{row.menu_name}}
			{% endfor %}	

			</span></a></li>
		</div>
	</div>
 </nav>
<div>
<ul id="dropdown1" class="dropdown-content">
  <li><a href={{ url_for('user_management.edituserprofile') }}>Your Profile</a></li>
  <li><a href={{ url_for('user_management.addresslist') }}>Your addresses</a></li>
   <li><a href={{ url_for('user_management.changepassword') }}>Change Password</a></li>
  <li><a href={{ url_for('user_management.wishlist') }}>Wish list</a></li>
  {%if current_user.userrole=='Admin'%}
  <li><a href={{ url_for('product_management.addmenu') }}>Add Menu</a></li>
   <li><a href={{ url_for('main_app.admin') }}>Admin</a></li>
  {%endif%}
  <li><a href="#!">Your Orders</a></li>
</ul>
</div>

<div>


{%for i in menus%}
<ul id="menu{{i.menu_id}}" class="dropdown-content">
		{%for j in submenu%}
			{% if i.menu_id==j.menu_id %}
			<li><a href={{ url_for('user_management.edituserprofile') }}>{{j.submenu_name}}</a></li>
			{% endif %}
		{% endfor %}

</ul>
 {% endfor %}


		
   