testarhamcollections_app/product_management/models.py
from ..extensions import db
import datetime
from flask import Flask, jsonify


#

class MenuMaster(db.Model):
    __tablename__ = 'menumaster'
    menu_id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    menu_name = db.Column(db.String(256), nullable=False)
    is_active = db.Column(db.Boolean, default=True)


class SubMenuMaster(db.Model):
    __tablename__ = 'submenumaster'
    submenu_id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    submenu_name = db.Column(db.String(256), nullable=False)
    menu_id = db.Column(db.Integer, db.ForeignKey('menumaster.menu_id'), nullable=False)
    is_active = db.Column(db.Boolean, default=True)


class CategoryMaster(db.Model):
    __tablename__ = 'categorymaster'

    category_id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    category_name = db.Column(db.String(512), nullable=False)
    submenu_id = db.Column(db.Integer, db.ForeignKey('submenumaster.submenu_id'), nullable=False)
    creation_date = db.Column(db.DateTime, default=datetime.datetime.utcnow())
    updation_date = db.Column(db.DateTime, onupdate=datetime.datetime.utcnow())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    parent_category = db.Column(db.Integer)


class ProductMaster(db.Model):
    __tablename__ = 'productmaster'

    product_id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    product_title = db.Column(db.String(1000))
    creation_date = db.Column(db.DateTime, default=datetime.datetime.utcnow())
    updation_date = db.Column(db.DateTime, onupdate=datetime.datetime.utcnow())
    is_live = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    soldoff_flag = db.Column(db.Boolean, default=False)
    cost_price = db.Column(db.Integer)
    price = db.Column(db.Integer)


class ProductImageMapping(db.Model):
    __tablename__ = 'productimagemapping'

    image_id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    image_name = db.Column(db.String(200))
    image_path = db.Column(db.String(512))
    main_image = db.Column(db.Boolean, default=False)
    creation_date = db.Column(db.DateTime, default=datetime.datetime.utcnow())
    updation_date = db.Column(db.DateTime, onupdate=datetime.datetime.utcnow())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    product_id = db.Column(db.Integer, db.ForeignKey('productmaster.product_id'), nullable=False)


# class ProductDetail(db.Model):
#     __tablename__ = 'productdetail'
#     product_detail_id = db.Column(db.Integer, autoincrement=True, primary_key=True)
#     product_id = db.Column(db.Integer, db.ForeignKey('product_master.product_id'), nullable=False)


class VoteTest(db.Model):
    __tablename__ = 'votetest'
    voteid = db.Column(db.Integer, autoincrement=True, primary_key=True)
    votenumber = db.Column(db.Integer)

testarhamcollections_app/product_management/forms.py
from flask_wtf import Form, FlaskForm
from wtforms import StringField, PasswordField, SelectField, DateField, BooleanField, validators


class AddProductForm(FlaskForm):
    product_title = StringField("Product Title")


class FormTest(FlaskForm):
    name = StringField("name")


class AddMenuForm(FlaskForm):
    menu_name = StringField("menu_name")
    is_active = BooleanField("is_active")


class AddSubmenuForm(FlaskForm):
    submenu_name = StringField("submenu_name")
    is_active = BooleanField("is_active")
    menu_id = SelectField('menu_id', coerce=int)

testarhamcollections_app/product_management/views.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, jsonify, session
from models import ProductMaster, MenuMaster, SubMenuMaster
from models import VoteTest
from flask_login import login_user, logout_user, login_required, current_user

from forms import AddProductForm, FormTest, AddMenuForm, AddSubmenuForm
from ..extensions import db
from werkzeug import secure_filename
import os
from flask_wtf.csrf import CsrfProtect

product_management = Blueprint('product_management', __name__, url_prefix="/", static_folder='./static', static_url_path="main_app/static", template_folder='./templates')
# from .extensions import db


@product_management.route("addproduct", methods=['POST', 'GET'])
@product_management.route("addproduct/<int:product_id>", methods=['POST', 'GET'])
@login_required
def addproduct(product_id=None):
    if product_id == None:
        form = AddProductForm()
        if form.validate_on_submit():
            addproduct = ProductMaster(product_title=form.product_title.data)
            db.session.add(addproduct)
            db.session.commit()
            return redirect(url_for('product_management.addproductimage', product_id=addproduct.product_id))
        return render_template("product_management/addproduct.html", form=form, product_id=product_id)
    else:
        productdata = ProductMaster.query.filter_by(product_id=product_id).first()
        form = AddProductForm(obj=productdata)
        form.populate_obj(productdata)
        if form.validate_on_submit():
            productdata.product_title = form.product_title.data
            db.session.add(productdata)
            db.session.commit()
            return redirect(url_for('product_management.addproductimage', product_id=product_id))
        return render_template("product_management/addproduct.html", form=form, product_id=product_id)
x

@product_management.route("addproductimage/<int:product_id>", methods=['POST', 'GET'])
def addproductimage(product_id):

    path = "/".join([os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')), "images", str(product_id)])

    if not os.path.exists(path):
        os.makedirs(path)

    for file in request.files.getlist('file'):
        filename = secure_filename(file.filename)
        destination = "/".join([path, filename])
        file.save(destination)

    return render_template("product_management/addproductimage.html", product_id=product_id)


@product_management.route("testjson/<int:id>", methods=['POST', 'GET'])
def testjson(id):
    list = [1, 2, 3]
    return jsonify(result=list)


@product_management.route('_add_numbers')
def add_numbers():
    a = request.args.get('a', 0, type=int)
    b = request.args.get('b', 0, type=int)
    return jsonify(result=a * b)


@product_management.route("addnumberpage", methods=['POST', 'GET'])
def addnumberpage():
    form = FormTest()
    return render_template("product_management/addnumber.html", form=form)


@product_management.route('something', methods=['post'])
def something():
    form = FormTest()
    if form.validate_on_submit():
        str1 = form.name.data
        cnt = str1.upper()
        print
        return jsonify(data1={'message': 'hello {}'.format(cnt)})
    return jsonify(data1=form.errors)


@product_management.route('voteexample', methods=['POST', 'GET'])
def voteexample():
    vt = VoteTest.query.filter_by(voteid=1).first()
    return render_template("product_management/voteexample.html", vt=vt)


@product_management.route('changevote/<vote>', methods=['POST', 'GET'])
def changevote(vote):
    vt1 = request.args.get('vote')
    vt = VoteTest.query.filter_by(voteid=1).first()
    vt.votenumber = vt.votenumber + int(vote)
    db.session.add(vt)
    db.session.commit()
    return jsonify(data=vt.votenumber)


@product_management.route('testajax', methods=['POST', 'GET'])
def testajax():
    clicked = None
    if request.method == "POST":
        clicked = request.get_json()
        clicked['clicked'] = "test successul"
        if clicked == None:
            clicked = "test"
        return jsonify(data=clicked)
    return render_template("product_management/testajax.html")


@product_management.route("menulist", methods=['POST', 'GET'])
@login_required
def menulist():
    menulist = db.engine.execute('CALL GET_MENU_LIST')
    x = menulist.fetchall()
    print(x)
    return render_template('product_management/menulist.html', menulist=x)

    # try:
    #     menulist = db.engine.execute('CALL GET_MENU_LIST')
    #     rows=menulist.fetchall()
    #     print('THIS IS COUNT OF ROW {} '.format(rows.__len__()))
    #     if rows.__len__()>0:
    #         print('test')
    #         return render_template('product_management/menulist.html', menulist=rows)
    #     else:
    #         return redirect(url_for('product_management.addmenu', menu_id=None))
    # except:
    #     return redirect(url_for('product_management.addmenu', menu_id=None))
    # return render_template('product_management/menulist.html', menulist=rows)


@product_management.route("addmenu", methods=['POST', 'GET'])
@product_management.route("addmenu/<int:menu_id>", methods=['POST', 'GET'])
@login_required
def addmenu(menu_id=None):
    if request.method == "POST":
        x = request.form.to_dict()
        try:
            x['is_active']
            x['is_active'] = True
        except KeyError:
            x['is_active'] = False
        if menu_id == None:
            try:
                menu = MenuMaster(menu_name=x['menu_name'], is_active=x['is_active'])
                db.session.add(menu)
                db.session.commit()
                return jsonify(success='Menu Added Successfully')
            except:
                error = 'Unable to add {}'.format(x['menu_name'])
                return jsonify(error=error)
        else:
            try:
                menu = MenuMaster.query.filter_by(menu_id=menu_id).first()
                menu.menu_name = x['menu_name']
                menu.is_active = x['is_active']
                db.session.add(menu)
                db.session.commit()
                return jsonify(success='Menu Updated Successfully')
            except:
                error = 'This record not found {}'.format(x['menu_name'])
                return jsonify(error=error)

    else:
        if menu_id == None:
            form = AddMenuForm()
            return render_template('product_management/addmenu.html', menu_id=menu_id, form=form)
        else:
            form = AddMenuForm()
            try:
                menudata = MenuMaster.query.filter_by(menu_id=menu_id).first()
                form = AddMenuForm(obj=menudata)
                form.populate_obj(menudata)
                return render_template('product_management/addmenu.html', menu_id=menu_id, form=form)
            except:
                return redirect(404)


@product_management.route('addsubmenu', methods=['POST', 'GET'])
@product_management.route("addsubmenu/<int:submenu_id>", methods=['POST', 'GET'])
@login_required
def addsubmenu(submenu_id=None):
    form = AddSubmenuForm()
    menulist = MenuMaster.query.all()
    if request.method == "POST":
        x = request.form.to_dict()
        try:
            x['is_active']
            x['is_active'] = True
        except KeyError:
            x['is_active'] = False
        if submenu_id == None:
            try:
                submenumaster = SubMenuMaster(submenu_name=x['submenu_name'], is_active=x['is_active'], menu_id=x['menu_id'])
                db.session.add(submenumaster)
                db.session.commit()
                return jsonify(success='Submenu Added Successfully')
            except:
                return jsonify(error='Submenu Addition Failed')
        else:
            try:
                submenudata = SubMenuMaster.query.filter_by(submenu_id=submenu_id).first()
                submenudata.submenu_name = x['submenu_name']
                submenudata.is_active = x['is_active']
                submenudata.menu_id = x['menu_id']
                db.session.add(submenudata)
                db.session.commit()
                return jsonify(success='Submenu Updated Successfully')
            except:
                return jsonify(error='Unable to fetch data')
    else:
        if submenu_id == None:
            return render_template('product_management/addsubmenu.html', submenu_id=submenu_id, form=form, menulist=menulist)
        else:
            try:
                submenudata = SubMenuMaster.query.filter_by(submenu_id=submenu_id).first()
                form = AddSubmenuForm(obj=submenudata)
                form.populate_obj(submenudata)
                return render_template('product_management/addsubmenu.html', submenu_id=submenu_id, form=form, menulist=menulist)
            except:
                return redirect(404)
                # return jsonify(error='Unable to fetch data')

testarhamcollections_app/product_management/templates/product_management/addmenu.html
{%extends 'main_app/base.html' %}
{% block content%}
<div class="col s12 m12 l12">
	<div class="row">
		<div class="row">
			<div class="card-panel grey lighten-2 col s12 m6 l4">
				<span class="red-text"><h5>Add Menu</h5>
				</span>
			</div>
		</div>
		<form  method="POST">
			<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
			<div class="row">
				<div class="row">
					<div class="input-field col s12 m6 l4">
						<input id="menu_name" type="text" name="menu_name" 
						value= {%if menu_id==None%}{{""}}{% else %}{{form.menu_name.data}}{% endif %}>
						<label for="menu_name">Menu</label>
					</div>
				</div>
				<div class="row">
					<div class="switch">
						<label>
						Off
						
						<input id="is_active" type="checkbox" name="is_active" {%if form.is_active.data==True%}{{'checked=checked'}}{%endif%}>
						
						<span class="lever"></span>
						On
						</label>
					</div>
				</div>
	      		<div class="row">
					<div class="input-field col s12 m6 l4">
						<button type="submit" id="savebutton" class="btn cyan waves-effect waves-light col s12">Save</button>
					</div>
				</div>
			</div>
			

		</form>

		<div class="col s12 m8 l6 offset-l3 m2">
		<div class="row">
			<div class="row" id ="success">
				 <div class="success-msg">
					
				 </div>					 
			</div>
			<div class="row" id ="error">
				 <div class="error-msg">
					
				 </div>					 
			</div>
		</div>
	</div>	

</div>

{% endblock%}
{% block endjs %}
<!-- <script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/jquery.min.js')}}"></script> -->

{{super()}}
<script>
	$(document).ready(function(event){
		
		$('#success').hide()
		$('#error').hide()
		var data;
		var tempurl;
		var url;
		var menu_id;
		url = "{{ url_for('product_management.addmenu',menu_id=menu_id)}}";
		
		// url=tempurl.replace('999999999','None');
				
		// alert(tempurl);

		$('form').on('submit',function(event){
				


				$.ajax({

					type:"POST",
					url:url,
					data: $('form').serialize()
					// success:function(data) {
     //            		$("#successmessage").html(data.success);
     //            		$('#success').removeClass('hide').addClass('show');
						
     //            		// alert('succcess');

					// 						},
					// error: function(error)	{
					// 	$("#errormessage").html(data.error);
					// 	$('#error').removeClass('hide').addClass('show')
						
						// alert('error');
											

					})
					.done(function(data){
						
						ShowMessage(data);
						
					});
			
				event.preventDefault();

			});


		});

		


</script>
{% endblock %}

testarhamcollections_app/product_management/templates/product_management/addnumber.html
{%extends 'main_app/base.html' %}

{% block content%}
<div class="row">
<form>
	{{form.name}}
	{{form.hidden_tag()}}
	<input type="submit" value="Go"/>
</form>
<div id="result"></div>
</div>


{% endblock %}

{% block endjs %}
<script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/jquery.min.js')}}"></script>
<script>
    $(document).ready(function() {
        $('form').submit(function (e) {
            var url = "{{ url_for('product_management.something') }}"; // send the form data here.
            $.ajax({
                type: "POST",
                url: url,
                data: $('form').serialize(), // serializes the form's elements.
                success: function (data) {
                    $("#result").text(data.data1.message);
                    console.log(data)  // display the returned data in the console.
                }

            });
            e.preventDefault(); // block the traditional submission of the form.
        });
        // Inject our CSRF token into our AJAX request.
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ form.csrf_token._value() }}")
                }
            }
        })
    });
</script>
{% endblock%}

testarhamcollections_app/product_management/templates/product_management/addproduct.html
{%extends 'main_app/base.html' %}
{% block content%}
<div class="row">
	<div class="row">
		<div class="card-panel grey lighten-2 col s12 m8 l8 offset-l2 m2">
			<span class="red-text"><h5>Add Product </h5>
			</span>
		</div>
	</div>
	<form action="{{url_for('product_management.addproduct',product_id=product_id)}}" method="POST">{{ form.csrf_token }}
		<div class="row">
			<div class="row">
				<div class="input-field col s12 m8 l8 offset-l2 m2">
					<input id="product_title" type="text" name="product_title" value= {%if product_id==None%}{{""}}{% else %}'{{form.product_title.data}}'{% endif %}>
					<label for="product_title">Product Title</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m8 l8 offset-l2 m2">
					<button type="submit" class="btn cyan waves-effect waves-light col s12">Proceed to step 2</button>
				</div>
			</div>
		</div>
	</form>
	{% with messages = get_flashed_messages() %}
		{% if messages %}
		    {% for message in messages %}
				<div class="row">
				<div class="chip  red lighten-5">
					{{ message }}
					<i class="close material-icons">close</i>
				</div>
				</div>
			{% endfor %}
		{% endif %}
	{% endwith %}
</div>
	


{% endblock%}

testarhamcollections_app/product_management/templates/product_management/addproductimage.html
{%extends 'main_app/base.html' %}
{% block content%}
<div class="row">
	<form action="{{ url_for('product_management.addproductimage', product_id=product_id) }}" method="POST" enctype="multipart/form-data">
		<input type="file" id"file" name="file">
		<button type="submit">Submit</button>
	</form>
</div>

{% endblock %}

testarhamcollections_app/product_management/templates/product_management/addsubmenu.html
{%extends 'main_app/base.html' %}
{% block content%}
<div class="col s12 m8 l6">
	<div class="row">
		<div class="row">
			<div class="card-panel grey lighten-2 col s12 m12 l12">
				<span class="red-text"><h5>Add Sub Menu</h5>
				</span>
			</div>
		</div>
		<form  method="POST">
			<div class="row">
				<div class="row">
					<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
					<div class="input-field col s12 m12 l12">
						<input id="submenu_name" type="text" name="submenu_name" value= {%if submenu_id==None%}{{""}}{% else %}{{form.submenu_name.data}}{% endif %}>
						<label for="submenu_name">Sub Menu</label>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s12 m12 l12">
						<select id="menu_id" name="menu_id">
						{%if submenu_id==None%}
						<option value="" disabled selected>Select Menu</option>
						{%endif%}

						
						{% for val in menulist %}
						<option value={{val.menu_id}} {%if submenu_id==None%}{""} {%else%}{"selected"}{%endif%}>{{val.menu_name}}</option>
						{%endfor%}
						</select>
						<label>Menu</label>
					</div>
				</div>
				<div class="row">
					<div class="switch">
						<label>
						Off
						<input id="is_active" type="checkbox" name="is_active"  {%if form.is_active.data==True%}{{'checked=checked'}}{%endif%}>
						<span class="lever"></span>
						On
						</label>
					</div>
				</div>

	      		<div class="row">
					<div class="input-field col s12 m12 l12">
						<button type="submit" class="btn cyan waves-effect waves-light col s12">Save</button>
					</div>
				</div>
			</div>
		</form>
	</div>

	<div class="col s12 m8 l6 offset-l3 m2">
		<div class="row">
			<div class="row" id ="success">
				 <div class="success-msg">
					
				 </div>					 
			</div>
			<div class="row" id ="error">
				 <div class="error-msg">
					
				 </div>					 
			</div>
		</div>
	</div>	

</div>


{% endblock%}

{% block endjs %}
{{super()}}
<script>


$(document).ready(function(event){
	$('#success').hide()
	$('#error').hide()

	var url;
	url = "{{ url_for('product_management.addsubmenu',submenu_id=submenu_id)}}";
	

	$('form').on('submit',function(event){

		$.ajax({
			type:"POST",
			url:url,
			data:$('form').serialize(),


		})
		.done(function(data){
						ShowMessage(data);
		});


	event.preventDefault();
	});


});
	
</script>

{% endblock %}

testarhamcollections_app/product_management/templates/product_management/addsubmenu1.html
{%extends 'main_app/base.html' %}
{% block content%}
<div class="col s12 m8 l6">
	<div class="row">
		<div class="row">
			<div class="card-panel grey lighten-2 col s12 m8 l6">
				<span class="red-text"><h5>Add Sub Menu</h5>
				</span>
			</div>
		</div>
		<form action="{{url_for('product_management.addsubmenu',submenu_id=submenu_id)}}" method="POST">{{ form.csrf_token }}
			<div class="row">
				<div class="row">
					<div class="input-field col s12 m6 l4">
						<input id="submenu_name" type="text" name="submenu_name" value= {%if submenu_id==None%}{{""}}{% else %}{{form.submenu_name.data}}{% endif %}>
						<label for="submenu_name">Sub Menu</label>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s12 m6 l4">
						<select id="menu_id" name="menu_id">
						{%if submenu_id==None%}
						<option value="" disabled selected>Select Menu</option>
						{%endif%}
						{% for val in menulist%}
						<option value={{val.menu_id}} {%if submenu_id==None%}{""} {%else%}{"selected"}{%endif%}>{{val.menu_name}}</option>
						{%endfor%}
						</select>
						<label>Menu</label>
					</div>
				</div>
				<!-- {{form.menu_id}} -->
				<div class="row">
					<div class="switch">
						<label>
						Off
						<input id="is_active" type="checkbox" name="is_active" {%if form.is_active.data ==True%}{{'checked=checked'}} {% endif %}/>
						<span class="lever"></span>
						On
						</label>
					</div>
				</div>

	      		<div class="row">
					<div class="input-field col s12 m6 l4">
						<button type="submit" class="btn cyan waves-effect waves-light col s12">Save</button>
					</div>
				</div>
			</div>
		</form>




		<!-- {% with messages = get_flashed_messages() %}
			{% if messages %}
			    {% for message in messages %}
					<div class="row">
					<div class="chip  red lighten-5">
						{{ message }}
						<i class="close material-icons">close</i>
					</div>
					</div>
				{% endfor %}
			{% endif %}
		{% endwith %} -->
	</div>

</div>

{% endblock%}

testarhamcollections_app/product_management/templates/product_management/menulist.html
{%extends 'main_app/base.html' %}
{% block content%}
<div class="row">

<table class="highlight responsive">
	<thead>
		<tr>
			<th>Menu Name</th>
			<th>Menu Status</th>
			<th>Submenu Name</th>
			<th>Submenu Status</th>
		</tr>
	</thead>
	<tbody>	
		{% for row in menulist %}
		<tr>
			<td><a href="{{ url_for('product_management.addmenu',menu_id=row.menu_id)}}">{{row.menu_name}}</a></td>
			<td>
				<div class="switch">
					<label>
					Off
					<input disabled type="checkbox" {% if row.menu_status %}{{'checked=checked'}}{%endif%}>
					<span class="lever"></span>
					On
					</label>
				</div>
			</td>
			
			<td>{%if row.submenu_name!=''%}
				<a href="{{ url_for('product_management.addsubmenu',submenu_id=row.submenu_id)}}">{{row.submenu_name}}</a>
				{%endif%}
			</td>
			
			<td>
			{%if row.submenu_name!=''%}
				<div class="switch">
					<label>
					Off
					<input disabled type="checkbox" {% if row.submenu_status %}{{'checked=checked'}}{%endif%}>
					<span class="lever"></span>
					On
					</label>
				</div>
			{%endif%}
			</td>
		</tr>
		{%endfor%}
	</tbody>
</table>
</div>
{% endblock%}

   

testarhamcollections_app/product_management/templates/product_management/testajax.html
{%extends 'main_app/base.html' %}

{% block content%}
<div>
	<a href="#" id ="test" name="Successfultest">TestAJAX </a>
</div>
{{form}}
<div id="success">
	
</div>
<form method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
</form>

{% endblock%}




{% block endjs %}
<script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/jquery.min.js')}}"></script>
<script>
    $(document).ready(function() {

       var clicked;
	
	$('#test').click(function(){
		clicked = $(this).attr("name");
		$.ajax({
					type: "POST",
					url : "{{url_for('product_management.testajax')}}",
					contentType: "application/json",
		            dataType: "json",
					data: JSON.stringify({"clicked":clicked}),
					success: function(result) 
							{
    						$("#success").html(result.data.clicked)
  							}
				});


								});
	  
	var csrf_token ="{{ csrf_token() }}";
	  $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrf_token)
                }
            }
        })
   
   	});

</script>
{% endblock%}

testarhamcollections_app/product_management/templates/product_management/testajax1.html
{%extends 'main_app/base.html' %}

{% block content%}
<div>
	<a href="#" id ="test" name="Successfultest">TestAJAX </a>
</div>
<div id="success">
	
</div>

{% endblock%}


{% block endjs %}
<script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/jquery.min.js')}}"></script>
<script>
    $(document).ready(function() {
       var clicked;
	$('#test').click(function(){
		clicked = $(this).attr("name");
		$.ajax({
					type: "GET",
					url : "{{url_for('product_management.testajax')}}",
					data: clicked
					success: function(result) 
							{
    						$("#success").html(result.data.clicked)
  							}
				});


								});
    								});
</script>
{% endblock%}

testarhamcollections_app/product_management/templates/product_management/voteexample.html
{%extends 'main_app/base.html' %}
{% block content%}

<div class="row">
	<div>
		<a href="#" id="upvote" value="1">
			<i class="material-icons">arrow_upward</i>
		</a>
			<div id="vote">{{vt.votenumber}}</div>
		<a href="#" id = "downvote" value="-1">
			<i class="material-icons">arrow_downward</i>
		</a>
	</div>
</div>
{% endblock %}
{%block endjs%}
<script  type="text/javascript" src="{{ url_for('main_app.static',filename='js/jquery.min.js')}}"></script>

<script>
	$(document).ready(function(){
		
		var vote;

		var url;
		var data;
		var tempurl;
		tempurl = "{{ url_for('product_management.changevote',vote='xxxxx')}}";
		url=tempurl.replace('xxxxx',vote)

		$('#upvote').click(function(){

			vote=$('#upvote').attr('value');

			url=tempurl.replace('xxxxx',vote)
			
			

			
			$.ajax({
				// type:'POST',
				type: "POST",
				url : url,
				dataType:"json",
				contentType: "application/json",
				data: JSON.stringify({'data':data}),

				success:function(data){
					$("#vote").html(data.data);
				},
				error: function(error){
					console.log(error);
				}

			});

		});

		$('#downvote').click(function(){

			vote=$('#downvote').attr('value');

			url=tempurl.replace('xxxxx',vote)
			;
			$.ajax({
				// type:'POST',
				type: "POST",
				url : url,
				dataType:"json",
				contentType: "application/json",
				data: JSON.stringify({'data':data}),

				success:function(data){
					$("#vote").html(data.data);
				},
				error: function(error){
					console.log(error);
				}

			});

		});
	
		var csrf_token ="{{ csrf_token() }}";
	  $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrf_token)
                }
            }
        })



	});

		


</script>

{% endblock %}